language: php

os: linux
dist: xenial

php:
  - "7.3"
  - "7.4"

before_install:
  - sudo apt-get update
  - sudo apt-get install make build-essential automake php-dev php-pear
  - git clone git://github.com/jedisct1/libsodium.git
  - cd libsodium
  - if [ ${TRAVIS_PHP_VERSION:0:3} == "7.2" ] || [ ${TRAVIS_PHP_VERSION:0:3} == "7.3" ] || [ ${TRAVIS_PHP_VERSION:0:3} == "7.4" ]; then
    git checkout 1.0.18;
    ./autogen.sh;
    ./configure && make check;
    sudo make install;
    cd ..;
    pecl install libsodium-2.0.22;
    fi

before_script:
  - php --version
  - composer install --prefer-source --no-interaction

script:
  - XDEBUG_MODE=coverage vendor/bin/phpspec --config=phpspec.yml run

after_script:
  - vendor/bin/codacycoverage clover build/coverage.xml