language: php

php:
  - 7.0

before_script:
 - git clone git://github.com/jedisct1/libsodium.git
 - cd libsodium
 - ./autogen.sh
 - ./configure --disable-dependency-tracking --enable-minimal
 - make
 - sudo make install
 - sudo /sbin/ldconfig
 - cd ..
 - rm -fr libsodium
 - composer install --prefer-source --no-interaction --dev

script:
 - phpize
 - ./configure --with-libsodium
 - make clean
 - make
 - env NO_INTERACTION=1 make test
 - vendor/bin/phpspec --config=phpspec.yml run