language: php

dist: xenial
sudo: required

php:
  - "7.0"
  - "7.1"
  - "7.2"
  - "7.3"

before_install:
  - sudo apt-get update
  - sudo apt-get install make build-essential automake php-dev php-pear
  - git clone git://github.com/jedisct1/libsodium.git
  - cd libsodium
  - if [ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ] || [ ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]; then
    git checkout 1.0.10;
    ./autogen.sh;
    ./configure && make check;
    sudo make install;
    cd ..;
    pecl install libsodium-1.0.7;
    fi
  - if [ ${TRAVIS_PHP_VERSION:0:3} == "7.2" ] || [ ${TRAVIS_PHP_VERSION:0:3} == "7.3" ]; then
    git checkout 1.0.18;
    ./autogen.sh;
    ./configure && make check;
    sudo make install;
    cd ..;
    pecl install libsodium-2.0.22;
    fi

before_script:
  - php --version
  - composer install --prefer-source --no-interaction

script:
  - vendor/bin/phpspec --config=phpspec.yml run

after_script:
  - vendor/bin/codacycoverage clover build/coverage.xml